- hosts: all
  vars:
    ansible_user: root
  tasks:
    - name: install sudo
      package:
        name: sudo
        state: installed

    - name: create mocops user
      user:
        name: mocops
        shell: /bin/bash

    - name: create sudo config for mocops user
      copy:
        content: |
          mocops ALL=(ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/mocops
        owner: root
        group: root
        mode: "0440"
